server:
  port: 8082
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url:
    username:
    data-password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**