server:
  port: 8082
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://10.90.181.191:3306/syshotel?characterEncoding=UTF8;allowMultiQueries=true&amp;autoReconnect=true
    username: root
    data-password: b6f3g2
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**