server:
  port: 8080
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

logging:
  config: classpath:logback-spring.xml
  path: ~/Logs/program-all/managment


spring:
  datasource:
    mater:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      url:
      username:
      data-password:
    slave_db1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      url:
      username:
      data-password:
    slave_db2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      url:
      username:
      data-password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**